kind: Deployment
apiVersion: apps/v1
metadata:
  name: profile-service
  namespace: ingress-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profileservice
          image: oefenpraktijkregistry.azurecr.io/profile:test
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: EventBusSettings__HostAddress
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: eventbus
            - name: MongoDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: mongo
          resources:
            limits:
              memory: 1000M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
